---
title: "Two-Way Anova Part 3"
author: "Siddharth V"
date: '2022-04-21'
output: html_document
---

## Load in the libraries
```{r}
library(tidyverse)
```

## Bring in the data
```{r}
## Creating a url for Jordan's career
mj_url <- read_html('https://www.basketball-reference.com/leagues/NBA_1991_per_game.html')

## Turning that information into a list
mj_info_lst = mj_url %>%
  html_nodes('#per_game_stats') %>%
  html_table()

## Creating a temporary data frame to hold the information from the list
temp_mj_df = mj_info_lst[[1]]

## Filtering out the season where he first won the championship and making that the lj data frame
mj_df_without_name = temp_mj_df %>%
  filter(Rk != 'Rk') %>%
  mutate_if(~any(str_detect(string = ., pattern = '^-?[0-9]\\d*(\\.\\d+)?$')),
            ~ as.numeric(.)) %>%
  distinct(Player,max(G),.keep_all = TRUE)

## Fixing column names
colnames(mj_df_without_name)[c(11,14,17,18,21)] = c('FG_percent', '3P_percent', '2P_percent', 'eFG_percent', 'FT_percent')

## Adding a column with the data frame name
mj_df = mj_df_without_name %>%
  mutate(df_name = 'MJ')

## Adding a new variable called binary_mp
mod1_mj_df = mj_df %>%
  mutate(Pos = as.factor(Pos),
    binary_mp = case_when(
    MP < 20 ~ 'few_mp',
    MP >= 20 ~ 'large_mp'
  ))

mod2_mj_df = subset(mod1_mj_df, Pos != 'SG-SF')
mod3_mj_df = subset(mod2_mj_df, Pos != 'SF-SG')
```

